### ISSUE TITLE
GetRawMemPool(true) throws exception

### ISSUE THREAD

**Issue by Leonardiae** [GeorgeKimionis/BitcoinLib#115]
When calling GetRawMemPool(true) it throws this exception:
{"Unkown property: fees in GetRawMemPool()"}

**Comment by moodmosaic** [comment]
Which Bitcoin Core version you're using? Also, can you send us the stack trace of the exception?

**Comment by Leonardiae** [comment]
I'm using 0.18.0

I'm a starter dev and don't know how to make a stack trace :( 
But this is my function:
        
static public void GetRawMempoolLocalNode()
        {
            try
            {

                IBitcoinService BitcoinService = new BitcoinService("localhost", "x", "x", "x", 2);
                var response = BitcoinService.GetRawMemPool(true);
            }
            catch (Exception exception)
            {
                        //
            }
        }

If I call GetRawMemPool without a parameter then I get results (a list of txid's).

**Comment by moodmosaic** [comment]
>I'm a starter dev and don't know how to make a stack trace :(

That's totally fine, we're more than happy to help :+1:  — So, in your `catch` block, trying doing something like `var err = exception.ToString();` and then hover your debugger there and copy the text.

Or do a `System.Console.WriteLine(exception.ToString());` and let us know what the output is.

---

That is,

```c#
catch (Exception exception)
{
    var err = exception.ToString();
    // What is the value of `err`?
}
```

or

```c#
catch (Exception exception)
{
    System.Console.WriteLine(exception.ToString());
    // What gets printed in the console?
}
```

**Comment by Leonardiae** [comment]
System.Exception: Unkown property: fees in GetRawMemPool()
   at BitcoinLib.Services.CoinService.GetRawMemPool(Boolean verbose)
   at Prog.Program.GetRawMempoolLocalNode() in C:\Users\Leonardiae\source\repos\Prog .netframework\Prog .netframework\Program.cs:line 71
