### ISSUE TITLE
Getting  - Dummy value must be set to "" - after some of the method calls

### ISSUE THREAD

**Issue by jhincapie** [GeorgeKimionis/BitcoinLib#120]
Hello, 

I am writing a little script to split coins from one address into four. So far, only using the testnet and BitcoinCore 0.21. When calling some of the methods returns the error 'Dummy value must be set to ""'. So, the method to getbalance works great, but the method sendmany fails. Here is an example of the output:

CoinSplitter
Balance: 0.02574542
Unhandled exception. BitcoinLib.ExceptionHandling.Rpc.RpcInternalServerErrorException: Dummy value must be set to ""
 ---> System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.GetResponse()
   at BitcoinLib.RPC.Connector.RpcConnector.MakeRequest[T](RpcMethods rpcMethod, Object[] parameters) in /home/jhincapie/Desktop/CoinSplitter/bitcoinlib/src/BitcoinLib/RPC/Connector/RpcConnector.cs:line 57
   --- End of inner exception stack trace ---
   at BitcoinLib.RPC.Connector.RpcConnector.MakeRequest[T](RpcMethods rpcMethod, Object[] parameters) in /home/jhincapie/Desktop/CoinSplitter/bitcoinlib/src/BitcoinLib/RPC/Connector/RpcConnector.cs:line 106
   at BitcoinLib.Services.CoinService.SendMany(String fromAccount, Dictionary`2 toBitcoinAddress, Int32 minConf, String comment) in /home/jhincapie/Desktop/CoinSplitter/bitcoinlib/src/BitcoinLib/Services/RpcServices/RpcService/RpcService.cs:line 621
   at CoinSplitter.Program.Main(String[] args) in /home/jhincapie/Desktop/CoinSplitter/Program.cs:line 41

Any ideas?

**Comment by moodmosaic** [comment]
Thanks for reporting this. Are you passing `--deprecatedrpc=accounts` to bitcoind when starting?

**Comment by jhincapie** [comment]
Hey, no I am just running:

/usr/local/bin/bitcoind -daemon -testnet

For the bitcoin.conf on the testnet I am using:

[test]
server=1
txindex=1
rpcbind=[ipaddress]
rpcallowip=0.0.0.0/0
rpcport=8332
rpcuser=[username]
rpcpassword=[password]
maxconnections=20

**Comment by jhincapie** [comment]
I do use a wallet called "CoinSplitter", which I manually load outside the program.

**Comment by moodmosaic** [comment]
Could you try with that setting I suggested?

**Comment by jhincapie** [comment]
Yeah, I did, no difference.

**Comment by unikaq** [comment]
Hello, I get also this with the command getbalance <bitcoin-adress> : "dummy first argument must be excluded or set to "*". This error also in console of bitcoin-core V22
