### ISSUE TITLE
SendToAddress error handling

### ISSUE THREAD

**Issue by hheexx** [GeorgeKimionis/BitcoinLib#18]
Is there a way to handle SendToAddress errors like fee too low?

All I get is RpcException:
BitcoinLib.ExceptionHandling.Rpc.RpcException: The RPC request was either not understood by the server or there was a problem executing the request ---> System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.GetResponse()
   at System.Net.HttpWebRequest.GetResponse()
   at BitcoinLib.RPC.Connector.RpcConnector.GetJsonResponse(HttpWebRequest httpWebRequest)
   --- End of inner exception stack trace ---
   at BitcoinLib.RPC.Connector.RpcConnector.MakeRpcRequest[T](JsonRpcRequest jsonRpcRequest, Int16 timedOutRequests)
   at BitcoinLib.RPC.Connector.RpcConnector.MakeRequest[T](RpcMethods rpcMethod, Object[] parameters)
....

Is there a way to access json response ?

**Comment by GeorgeKimionis** [comment]
This is now resolved with the use of `RpcInternalServerErrorException()` that handles internal server error exceptions and rebroadcast both the error message as well as the RPC error code.

**Comment by hheexx** [comment]
Now I can see whats wrong from stack trace :)

Thanks!
