### ISSUE TITLE
GetBlockTemplate not working (deserialization)

### ISSUE THREAD

**Issue by jflecool2** [GeorgeKimionis/BitcoinLib#21]
Although the Json request is done and retreived, GetBlockTemplate crash when the lib is trying to deserialize...

Thanks

BitcoinLib.ExceptionHandling.Rpc.RpcResponseDeserializationException was unhandled
  HResult=-2146233088
  Message=There was a problem deserializing the response from the wallet
  Source=BitcoinLib
  StackTrace:
       at BitcoinLib.RPC.Connector.RpcConnector.MakeRequest[T](RpcMethods rpcMethod, Int16 timedOutRequestsCount, Object[] parameters) in g:\Downloads\BitcoinLib-master\BitcoinLib-master\CoinWrapper\RPC\RequestResponse\RpcConnector.cs:line 166
       at BitcoinLib.RPC.Connector.RpcConnector.MakeRequest[T](RpcMethods rpcMethod, Object[] parameters) in g:\Downloads\BitcoinLib-master\BitcoinLib-master\CoinWrapper\RPC\RequestResponse\RpcConnector.cs:line 31
       at BitcoinLib.Services.CoinService.GetBlockTemplate(Object[] parameters) in g:\Downloads\BitcoinLib-master\BitcoinLib-master\CoinWrapper\Services\RpcServices\RpcService\RpcService.cs:line 165
       at ConsoleClient.Program.Main() in g:\Downloads\BitcoinLib-master\BitcoinLib-master\ConsoleClient\Program.cs:line 38
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: Newtonsoft.Json.JsonReaderException
       HResult=-2146233088
       Message=Error reading string. Unexpected token: StartObject. Path 'result', line 1, position 11.
       Source=Newtonsoft.Json
       LineNumber=1
       LinePosition=11
       Path=result
       StackTrace:
            at Newtonsoft.Json.JsonReader.ReadAsStringInternal()
            at Newtonsoft.Json.JsonTextReader.ReadAsString()
            at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
            at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
            at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
            at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
            at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
            at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
            at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
            at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
            at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
            at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
            at BitcoinLib.RPC.Connector.RpcConnector.MakeRequest[T](RpcMethods rpcMethod, Int16 timedOutRequestsCount, Object[] parameters) in g:\Downloads\BitcoinLib-master\BitcoinLib-master\CoinWrapper\RPC\RequestResponse\RpcConnector.cs:line 80
       InnerException:

**Comment by GeorgeKimionis** [comment]
Thanks for reporting this issue. It's very strange that you get this error, though, as the signature for `GetBlockTemplate` is: `String GetBlockTemplate(params object[] parameters);` so the response is being cast to a string and not to a strongly-typed structure.

Could you please provide me with the request's details? Are you on testnet?

**Comment by jflecool2** [comment]
I am. Crash at RpcConnector.cs:80. Heres the code I made
        ICoinService CoinService = new BitcoinService(useTestnet:true);
        CoinService.GetBlockTemplate();
The value of result on RpcConnector.cs:74 is:
{"result":{"version":2,"previousblockhash":"0000000000000257c44b592540c7ca1ca58338c8b411dae12e2e93d11d880c55","transactions":[{"data":"0100000001b8c34c37ee59123cb6e4088d4d3e5edc3b228df82dd5182ff7100ecb0c4e1ba3010000006a4730440220416c35df2bf0a7f406ffee16048201d2d5d6330e406e1f1330cca7513658fb52022042d9eb7eb1733c085a9bb9f3c07b2b93fca01a62e951291c521c3ae6a8206d940121025f54676f21f33f8eadcf4d452bf5df7875343bcd5f5d7cc68c92a18163623458ffffffff0200000000000000002a6a28466163746f6d21216aab8a1a621dced9b12521883aaa3ba43d0d01caaf9ee1749626529403b6dc980029fc02000000001976a914bd1a23d1afaede2e77a5004975f811592cc5bfac88ac00000000","hash":"ba9accfce030ea5cdd0d49945e51b02e0c99825877773450f1a9c76cc98996f3","depends":[],"fee":10000,"sigops":1},{"data":"01000000010ea0a388ddb17fc9e9029d8fb13f62abbaf47df5b6da9a541d97c579f89ade89000000008b4830450220692396185005aabd5ebee2d8c6f1d3b6c34cbc0fbff71ff70b96f582b53f5aa9022100fcdbf41127e8a89ff59e9b5b309521d1e355f9717be896941d69e022ee5979a90141047d14d722337adee31654b76e5f9ba6bf90d9457cae909a67c037f2f5db5012ba238615fffd0bd278c7484931006b495a6c9df3a7c07d1fe5ce218ace04f89f10ffffffff02ece90600000000001976a914cd2b1563d37f40a33588298a5e95c5760f9e1b2188acf87d0700000000001976a91442357b32aa40b7692bc97edf1812ee18fd4504d288ac00000000","hash":"bc18769ada0b8861e3503ff5ee5cc2f1bb5b89a86b4c234fc4fa0c3eb3922a3c","depends":[],"fee":100000,"sigops":2}],"coinbaseaux":{"flags":"062f503253482f"},"coinbasevalue":2500110000,"target":"00000000000002b9e90000000000000000000000000000000000000000000000","mintime":1427567985,"mutable":["time","transactions","prevblock"],"noncerange":"00000000ffffffff","sigoplimit":20000,"sizelimit":1000000,"curtime":1427567985,"bits":"1a02b9e9","height":329366},"error":null,"id":1}

**Comment by GeorgeKimionis** [comment]
I guess it's the `:` on column 11 that causes this issue.

Here is the [JsonConvert.DeserializeObject Method](http://www.newtonsoft.com/json/help/html/M_Newtonsoft_Json_JsonConvert_DeserializeObject_4.htm) specifications. Perhaps a `JsonSerializerSettings` should be deployed for the `GetBlockTemplate` case. 

Ideas?

**Comment by jflecool2** [comment]
First, I don't understand why the : would break the deserialize method. This is perfecly valid Json data. No?
Second, Is there a reason GetWork has not been put into this library ? Is it because it has been "replaced" by GetBlockTemplate?

**Comment by GeorgeKimionis** [comment]
`GetWork` was removed in v.0.10 (commit: cf0c47b), this is why it was also removed by this library.

Well according to the exception thrown this is what breaks the deserialization: `"Error reading string. Unexpected token: StartObject. Path 'result', line 1, position 11."`.

More people have stumbled upon this issue:
https://www.google.com/search?q=newtonsoft.json+Error+reading+string.+Unexpected+token:+StartObject

**Comment by jflecool2** [comment]
I have no experience in csharp json deserialization ... :(
I'm on something else, when i'll be done i'll come back and try to find a hack to fix it.

**Comment by GeorgeKimionis** [comment]
Maybe it's something simple, or maybe not. My time is also very limited at the moment so I would appreciate it if you could take a closer look whenever you find some time.

**Comment by jflecool2** [comment]
Will not make a pull request right now because my code is ugly but I figured it out: It was needed to make a Response object like you did in the Responses folder. It now work like a charm. Will attempt to make a pull request soon, but got stuff on my plate, such as finishing this project for university (bitcoin miner in csharp) :)

**Comment by jflecool2** [comment]
Can you tell me if I should put JsonProperty on my Response object or they are useless? It worked with them here, but none of your response object has it. or at least, a very few. 

Also, does the variable name has to match ? (noncerange VS NonceRange VS Nonce_Range)?

Thanks

**Comment by GeorgeKimionis** [comment]
That's great news, well done.

You should only use `JsonProperty` in the case that you need to assign a different name to your class member, for example take a look at the [GetInfoResponse class](https://github.com/GeorgeKimionis/BitcoinLib/blob/26d2e822cd974bd30cd472e4c476a89011d5edc1/CoinWrapper/Responses/GetInfoResponse.cs), the RPC API returns a `unlocked_until` field which doesn't match the camelcase naming convention used throughout the project so `JsonProperty` is enforced to create a match between RPC API's `unlocked_until` and the local field `UnlockedUntil`.

**Comment by jflecool2** [comment]
What do you think ?

**Comment by GeorgeKimionis** [comment]
Fixed with https://github.com/GeorgeKimionis/BitcoinLib/pull/22
