### ISSUE TITLE
Unhandled Exception: System.IO.FileNotFoundException on BitcoinService Initialization

### ISSUE THREAD

**Issue by nixxholas** [GeorgeKimionis/BitcoinLib#53]
Seems like your library is not friendly to predefined objects..

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

   at BitcoinLib.Services.CoinService.CoinParameters..ctor(ICoinService coinService, String daemonUrl, String rpcUsername, String rpcPassword, String walletPassword, Int16 rpcRequestTimeoutInSeconds)
   at BitcoinLib.Services.CoinService..ctor(String daemonUrl, String rpcUsername, String rpcPassword, String walletPassword, Int16 rpcRequestTimeoutInSeconds)
   at WalletServer.Program.Main(String[] args) in
```

And in case you assume ApplicationSettings could be invalid:
![screen shot 2017-12-07 at 4 31 11 pm](https://user-images.githubusercontent.com/4703269/33705679-36faa674-db6c-11e7-9896-bae55a92fdf0.png)

```
// Bitcoind
            _BitcoinService = new BitcoinService(ApplicationSettings.GetEncryptedString("BTCNodeDaemonURL"),
                                                 ApplicationSettings.GetEncryptedString("BTCNodeJsonRPCUser"),
                                                 ApplicationSettings.GetEncryptedString("BTCNodeJsonRPCPass"),
                                                "", 10);
```

**Comment by nixxholas** [comment]
Apologies. Seems like .NET Core 2.0 isn't supported.
